# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScreenTransactionExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'SemiModalViewController'
  # Pods for ScreenTransactionExample

  target 'ScreenTransactionExampleTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'SemiModalViewController'
  end

  target 'ScreenTransactionExampleUITests' do
    # Pods for testing
  end

end
