# Uncomment the next line to define a global platform for your project
# platform :ios, '15.5'

target 'rxCounterExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rxCounterExample
	# MARK : - UI
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxAppState', '~> 1.7.1'

  target 'rxCounterExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxCounterExampleUITests' do
    # Pods for testing
  end

end
